export {default as About} from './About/About'
export {default as Contact} from './Contact/Contact'
export {default as Blogs} from './Blogs/Blogs'
export {default as Footer} from './Footer/Footer'
export {default as Hero} from './Hero/Hero'
export {default as Menu} from './Menu/Menu'